import Head from 'next/head'
import Nav from '@/components/nav'
import HomePage from '@/components/home'
import Team from '@/components/team'
import Footer from '@/components/footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Nav />
        <HomePage />
        <Team />
        <Footer />
      </main>
    </>
  )
}
